runtime: nodejs12

instance_class: F2

handlers:
  - url: /uu-strava-maing01/9cb6f576dcb44633b5d7e5afd9384a49/public
    static_dir: public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
