runtime: nodejs12

entrypoint: node app.js

instance_class: F1

handlers:
  - url: /public
    static_dir: public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
